### PR TITLE
Added content from meetup, major template changes

### PR DESCRIPTION
**Pull request by earthastronaut**
This is a major overhaul. I incorporated my new package django-meetup to sync the SLCPython meetup to a local database which is then used to provide content on the webpage.

I reformatted the website to the home page with next upcoming event and an events page listing all events.
Note: Not committed at all to color-scheme, maybe a group decision later? :1234:

### CODE REVIEW

**Comment by octaflop** [comment]
Excellent work!

I'll have a closer look tonight. 

A couple notes from a cursory glance:
- [Arrow](crsmithdev.com/arrow/) is a phenomenal datetime library with great humanization and timezone support.
- I'm a huge fan of [sass](http://sass-lang.com/) and [compass](http://compass-style.org/) and would recommend using them for our css generation.
- I'd like to use django 1.7 because 1.4 long term support is only guaranteed through March 2015 and using 1.7 would put us in the best position for the next long term release → this might be the next thing we explore before we get too far ahead with development.

**Comment by earthastronaut** [comment]
I'm down with sass and compass. I think the css can use be overhauled. Arrow looks good, I did some humanizing of times myself. It'd be nice to lean on something else for that.

I'm also up for making this django 1.7 :+1:  (I've also been doing my best to make this easy to move to python3).

**Comment by octaflop** [comment]
Oh, one more thing. In the [settings](https://github.com/SLCPython/slcpy.com/pull/5/files#diff-dc286de1b372eab0d1abc11f95a9c40dL79) stick to UTC for the timezone for now. It's much easier to start with UTC even though we're in `America/Denver`

**Comment by earthastronaut** [comment]
This PR is now different from when it started. I deleted my own django-meetup app with local database syncing, in favor of a SLCPy dependent (sort of) meetup app located in /slcpy.com/apps/meetup  which handles all meetup logic. I.e. the basic difference is when a page is loaded api.meetup.com is queried not our local database.

<strong>Though the end result is the same I think this is much cleaner. </strong>

I also removed the profiles app mostly because I don't see us needing any user login for protected content since this webpage is mostly a gateway to Meetup.com and our meetup is public.

I still haven't incorporated : 
- Django  1.7
- sass/compass 
- etherpad urls (though some functions were added to help with)

**Pull request closed without merging**
